export const ROUTES = {
  SIGN_UP: 'SignUp',
  LOG_IN: 'LogIn',
  SETTINGS: 'SettingsScreen',
  HOME: 'PatientSpecificDashboard',
  PATIENT_SPECIFIC_DASHBOARD: 'PatientSpecificDashboard',
  CAREGIVER_HOME: 'MainDashboardCaregiver',
  APPOINTMENT_TRACKER: 'ApptTracker',
  MED_TRACKER: 'MedTracker',
  PROGRESS_REPORT: 'ProgressReport',
  HELP_AND_SUPPORT: 'HelpAndSupport',
  NOTIFICATION: 'NotificationScreen',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
  ACCESSIBILITY: 'Accessibility',
  ACCESSIBILITY_SETTINGS: 'AccessibilitySettings',
  PROFILE: 'ProfileScreen',
  EDIT_PROFILE: 'EditProfileScreen',
  PRIVACY_SETTINGS: 'PrivacySettings',
  LINK_TO_CAREGIVER: 'LinkToCaregiver',
  LINK_TO_PATIENT_MAIN: 'LinktoPatientMainPage',
  LINK_REQUESTS: 'LinkRequestsPage',
  PRACTICE_GROUND: 'PracticeGround',
};
