export const ROUTES = {
  SIGN_UP: 'SignUp',
  LOG_IN: 'LogIn',
  SETTINGS: 'SettingsScreen',
  HOME: 'PatientSpecificDashboard',
  PATIENT_SPECIFIC_DASHBOARD: 'PatientSpecificDashboard',
  CAREGIVER_HOME: 'MainDashboardCaregiver',
  APPOINTMENT_TRACKER: 'ApptTracker',
  MED_TRACKER: 'MedTracker',
  MED_TRACKER_HISTORY: 'MedTrackerHistory',
  HELP_AND_SUPPORT: 'HelpAndSupport',
  ACCESSIBILITY_SETTINGS: 'AccessibilitySettings',
  PROFILE: 'ProfileScreen',
  PRIVACY_SETTINGS: 'PrivacySettings',
  LINK_TO_CAREGIVER: 'LinkToCaregiver',
  LINK_TO_PATIENT_MAIN: 'LinkToPatientMainPage',
  LINK_REQUESTS: 'LinkRequestsPage',
};
