export const ROUTES = {
  SIGN_UP: 'SignUp',
  LOG_IN: 'LogIn',
  LOADING: 'Loading',
  PROFILE_SETUP: 'ProfileSetup',
  SETTINGS: 'SettingsScreen',
  HOME: 'PatientDashboard',
  PATIENT_DASHBOARD: 'PatientDashboard',
  APPOINTMENT_TRACKER: 'ApptTracker',
  APPOINTMENT_TRACKER_HISTORY: 'ApptTrackerHistory',
  MED_TRACKER: 'MedTracker',
  MED_TRACKER_HISTORY: 'MedTrackerHistory',
  HELP_AND_SUPPORT: 'HelpAndSupport',
  ACCESSIBILITY_SETTINGS: 'AccessibilitySettings',
  PROFILE: 'ProfileScreen',
};
